export type NodeKind = "dir" | "file" | "symlink";

export type TreeNode = {
  name: string;
  path: string;
  kind: NodeKind;
  description: string;
  tag?: string;
  children?: TreeNode[];
};

export const harnessTree: TreeNode = {
  name: ".ai",
  path: ".ai",
  kind: "dir",
  tag: "harness",
  description:
    "AgentFactory harness root. All CLI adapters, agents, skills, rules, and memory live here. Scaffolded by `agentfactory-gen init` — never edit manually outside of the CLI workflow.",
  children: [
    {
      name: "AgentFactory.md",
      path: ".ai/AgentFactory.md",
      kind: "file",
      tag: "source-of-truth",
      description:
        "Shared context file loaded by every CLI adapter (Claude, Gemini, Codex). Contains harness overview, registered agents, behavior rules, and available commands. Keep it under ~6 KB to stay within adapter token budgets.",
    },
    {
      name: "adapters",
      path: ".ai/adapters",
      kind: "dir",
      tag: "adapters",
      description:
        "Per-CLI adapter configurations. Each subdirectory wires a specific AI CLI to the shared harness via symlinks and per-CLI config files. Adding a new CLI means adding a new adapter directory here.",
      children: [
        {
          name: "claude",
          path: ".ai/adapters/claude",
          kind: "dir",
          description:
            "Claude Code adapter. `commands` and `skills` symlinks expose shared capabilities. `brief.md` is the compiled Claude-specific context brief injected into CLAUDE.md.",
          children: [
            {
              name: "brief.md",
              path: ".ai/adapters/claude/brief.md",
              kind: "file",
              description:
                "Compiled Claude-specific context brief, generated by `agentfactory-gen sync`. Contains harness overview formatted for Claude Code's CLAUDE.md injection.",
            },
            {
              name: "commands →",
              path: ".ai/adapters/claude/commands",
              kind: "symlink",
              description:
                "Symlink → `../../commands`. Exposes shared command definitions to Claude Code as slash commands. Any command dropped in the global commands/ directory becomes available here automatically.",
            },
            {
              name: "skills →",
              path: ".ai/adapters/claude/skills",
              kind: "symlink",
              description:
                "Symlink → `../../skills`. Exposes global skills to Claude's project skill loader. No copy needed — skills are shared from the single source.",
            },
            {
              name: "settings.json",
              path: ".ai/adapters/claude/settings.json",
              kind: "file",
              description:
                "Claude Code project settings — permissions, hook configuration, and harness-level behavior overrides.",
            },
          ],
        },
        {
          name: "codex",
          path: ".ai/adapters/codex",
          kind: "dir",
          description:
            "OpenAI Codex adapter. `prompts` symlink maps shared commands. `config.toml` sets model name and context window parameters. `brief.md` uses Codex's AGENTS.md skill-declaration format.",
          children: [
            {
              name: "brief.md",
              path: ".ai/adapters/codex/brief.md",
              kind: "file",
              description:
                "Codex-specific compiled brief. Uses AGENTS.md skill-declaration syntax instead of CLAUDE.md format — generated by the FormatSwitch adapter during `agentfactory-gen sync`.",
            },
            {
              name: "config.toml",
              path: ".ai/adapters/codex/config.toml",
              kind: "file",
              description:
                "Codex configuration — model string, approval mode, and the path to the shared context file.",
            },
            {
              name: "prompts →",
              path: ".ai/adapters/codex/prompts",
              kind: "symlink",
              description:
                "Symlink → `../../commands`. Maps shared command definitions into Codex's prompts directory format.",
            },
            {
              name: "skills →",
              path: ".ai/adapters/codex/skills",
              kind: "symlink",
              description:
                "Symlink → `../../skills`. Exposes global skills to Codex.",
            },
          ],
        },
        {
          name: "gemini",
          path: ".ai/adapters/gemini",
          kind: "dir",
          description:
            "Google Gemini CLI adapter. `tools` symlink exposes skills as Gemini tool definitions. `config.json` sets model and temperature.",
          children: [
            {
              name: "brief.md",
              path: ".ai/adapters/gemini/brief.md",
              kind: "file",
              description:
                "Gemini-specific compiled context brief.",
            },
            {
              name: "config.json",
              path: ".ai/adapters/gemini/config.json",
              kind: "file",
              description:
                "Gemini adapter configuration — model name, temperature, and context file path.",
            },
            {
              name: "tools →",
              path: ".ai/adapters/gemini/tools",
              kind: "symlink",
              description:
                "Symlink → `../../skills`. Maps global skills into Gemini's tool-call format.",
            },
          ],
        },
      ],
    },
    {
      name: "agents",
      path: ".ai/agents",
      kind: "dir",
      tag: "agents",
      description:
        "Registered agents. Each subdirectory is a Portable Unit with the standard 5-directory structure: `commands/`, `docs/`, `orchestration/`, `scripts/`, `skills/`, and an `agent-manifest.json`. Created by `agentfactory-gen deploy`.",
      children: [
        {
          name: "test-agent",
          path: ".ai/agents/test-agent",
          kind: "dir",
          description:
            "Minimal test agent demonstrating the standard Portable Unit layout. Useful as a scaffold reference when authoring new agents.",
          children: [
            {
              name: "agent-manifest.json",
              path: ".ai/agents/test-agent/agent-manifest.json",
              kind: "file",
              description:
                "Agent manifest — name, version, description, declared dependencies, and capabilities. The Librarian validates this against the global agent-manifest.json on every audit.",
            },
            {
              name: "commands/",
              path: ".ai/agents/test-agent/commands",
              kind: "dir",
              description: "Agent-specific slash command definitions, local to this agent.",
            },
            {
              name: "docs/",
              path: ".ai/agents/test-agent/docs",
              kind: "dir",
              description: "Agent documentation and contextual reference files.",
            },
            {
              name: "scripts/",
              path: ".ai/agents/test-agent/scripts",
              kind: "dir",
              description: "Automation scripts used exclusively by this agent.",
            },
            {
              name: "skills/",
              path: ".ai/agents/test-agent/skills",
              kind: "dir",
              description: "Agent-local skills — not surfaced globally, only available within this agent's context.",
            },
          ],
        },
        {
          name: "test-intel-agent",
          path: ".ai/agents/test-intel-agent",
          kind: "dir",
          description:
            "Intelligence-layer demo agent. Demonstrates dependency detection and skill manifest parsing via the Librarian's AST analysis pipeline.",
        },
        {
          name: "test-claude-agent",
          path: ".ai/agents/test-claude-agent",
          kind: "dir",
          description:
            "Minimal Claude-native agent. Demonstrates a clean Claude Code-first layout with no cross-CLI adapter overhead.",
        },
      ],
    },
    {
      name: "commands",
      path: ".ai/commands",
      kind: "dir",
      description:
        "Shared slash command definitions. Each `.md` file defines a command available to all wired CLI adapters via their `commands →` symlinks. Drop a file here to expose a new command to every adapter simultaneously.",
    },
    {
      name: "memory",
      path: ".ai/memory",
      kind: "dir",
      tag: "memory",
      description:
        "Persistent project memory. `milestones.md` is the single source of truth for issue traceability. `project-context.md` holds stable architectural context loaded on every session.",
      children: [
        {
          name: "milestones.md",
          path: ".ai/memory/milestones.md",
          kind: "file",
          description:
            "Living traceability matrix. Tracks every issue — pending, in-progress, and completed — with branch, PR, commit, and tag columns. Updated on every merge per the git-versioning skill's Step 8.5.",
        },
        {
          name: "project-context.md",
          path: ".ai/memory/project-context.md",
          kind: "file",
          description:
            "Stable project context — purpose, architecture overview, and non-obvious conventions that should inform every Claude session.",
        },
      ],
    },
    {
      name: "rules",
      path: ".ai/rules",
      kind: "dir",
      tag: "rules",
      description:
        "Governance rules injected into the harness context. Each file enforces a specific behavior class: CLI conventions, git workflow, testing standards, security requirements, skill-briefing format, and milestone tracking.",
      children: [
        {
          name: "cli.md",
          path: ".ai/rules/cli.md",
          kind: "file",
          description: "CLI behavior rules — quiet flags, command conventions, error handling standards.",
        },
        {
          name: "git.md",
          path: ".ai/rules/git.md",
          kind: "file",
          description: "Git workflow rules — branch naming, commit message format, PR and merge requirements.",
        },
        {
          name: "milestones.md",
          path: ".ai/rules/milestones.md",
          kind: "file",
          description: "Traceability enforcement — every issue must appear in milestones.md; rows must be updated on every PR merge.",
        },
        {
          name: "security.md",
          path: ".ai/rules/security.md",
          kind: "file",
          description: "Security rules — no secrets in logs or commits, input sanitization, URL and path validation requirements.",
        },
        {
          name: "testing.md",
          path: ".ai/rules/testing.md",
          kind: "file",
          description: "Testing standards — 80% coverage gate, integration test requirements, test organization conventions.",
        },
        {
          name: "skill-briefing.md",
          path: ".ai/rules/skill-briefing.md",
          kind: "file",
          description: "Skill metadata format rules — keeps description and trigger fields brief-safe for compiled context injection.",
        },
        {
          name: "docs.md",
          path: ".ai/rules/docs.md",
          kind: "file",
          description: "Documentation standards — version markers required in all `.md` files, DEVLOG format and update cadence.",
        },
      ],
    },
    {
      name: "scripts",
      path: ".ai/scripts",
      kind: "dir",
      tag: "scripts",
      description:
        "Automation scripts for harness operations. `harness-doctor.sh` is the live health checker — validates harness structure, token budgets, adapter wiring, and version markers.",
      children: [
        {
          name: "harness-doctor.sh",
          path: ".ai/scripts/harness-doctor.sh",
          kind: "file",
          description:
            "Live harness health checker. Validates: harness root, AgentFactory.md token budget, global manifest JSON, adapter symlinks, skills aggregate size, and version markers. Exit codes: 0=clean, 1=warnings, 2=critical. Run with `--ci` for JSON snapshot output.",
        },
      ],
    },
    {
      name: "skills",
      path: ".ai/skills",
      kind: "dir",
      tag: "skills",
      description:
        "Global skills shared across all agents and adapters. Each skill has a versioned `SKILL.md` and a `references/` directory for supporting data files.",
      children: [
        {
          name: "diff-visualizer",
          path: ".ai/skills/diff-visualizer",
          kind: "dir",
          description:
            "Generates self-contained HTML diff reports between repo versions using Mermaid diagrams. Compares full repository state and writes a visual changelog to `assets/`.",
        },
        {
          name: "git-versioning",
          path: ".ai/skills/git-versioning",
          kind: "dir",
          description:
            "Git and versioning workflow assistant. Handles commit, branch, PR, merge, tag, release, and rollback. Reads all project-specific values from `references/repo-state.md` — no hardcoded names.",
        },
      ],
    },
  ],
};
